name: Test Go
on: [push, pull_request]
jobs:
  lint-test-build:
    name: Lint, Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16.2'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Dependencies
      env:
        GOPROXY: https://proxy.golang.org,direct
      run: go mod download

    - name: Test
      run: go test -tags unit -race ./...
